# -*- mode: ruby -*-
# vi: set ft=ruby :
Vagrant.configure(2) do |config|
  config.vm.box = "bento/ubuntu-18.10"

  # config.vm.network "forwarded_port", guest: 80, host: 8080

  # config.vm.network "private_network", ip: "192.168.33.10"

  # config.vm.network "public_network"

  config.vm.synced_folder "../shared", "/mnt/shared"
  config.vm.define "ubuntu-18.10-bento"

  config.vm.provider "virtualbox" do |vb|
    vb.gui = false
    vb.memory = "4096"
  end

  config.vm.provider "libvirt" do |lv|
    lv.memory = "1024"
    lv.keymap = "en"
  end

# Configure ansible
#  config.vm.provision "ansible_local" do |ansible|
#    ansible.verbose = "v"
#    ansible.playbook = "/etc/ansible/ansible-modules/jenkins.yml"
#  end

end
